{
 "title": "System",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "cpu %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - max (rate(node_cpu_seconds_total{job=\"macos\",mode=\"idle\"}[$__rate_interval]))",
     "legendFormat": "min"
    },
    {
     "expr": "1 - min (rate(node_cpu_seconds_total{job=\"macos\",mode=\"idle\"}[$__rate_interval]))",
     "legendFormat": "max"
    },
    {
     "expr": "1 - avg (rate(node_cpu_seconds_total{job=\"macos\",mode=\"idle\"}[$__rate_interval]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_wired_bytes{job=\"macos\"}",
     "legendFormat": "wired"
    },
    {
     "expr": "node_memory_active_bytes{job=\"macos\"}",
     "legendFormat": "active"
    },
    {
     "expr": "node_memory_compressed_bytes{job=\"macos\"}",
     "legendFormat": "compressed"
    },
    {
     "expr": "node_memory_inactive_bytes{job=\"macos\"}",
     "legendFormat": "inactive"
    },
    {
     "expr": "node_memory_free_bytes{job=\"macos\"}",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "swap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_swap_used_bytes{job=\"macos\"}",
     "legendFormat": "used"
    },
    {
     "expr": "node_memory_swap_total_bytes{job=\"macos\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "cpu % per core",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - rate(node_cpu_seconds_total{job=\"macos\", mode=\"idle\"}[$__rate_interval])",
     "legendFormat": "cpu {{cpu}}"
    }
   ]
  },
  {
   "title": "disk i/o",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "-rate(node_disk_read_bytes_total{job=\"macos\", device=\"disk0\"}[$__rate_interval])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{job=\"macos\", device=\"disk0\"}[$__rate_interval])",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "network throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "-rate(node_network_receive_bytes_total{job=\"macos\", device=\"en0\"}[$__rate_interval])",
     "legendFormat": "{{device}} rx"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"macos\", device=\"en0\"}[$__rate_interval])",
     "legendFormat": "{{device}} tx"
    }
   ]
  }
 ]
}